name: Beta Deploy to cPanel

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Build & SSH Deploy
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: â¬‡ï¸ Install dependencies
        run: pnpm install

      - name: ðŸ› ï¸ Build Next.js application
        env:
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
        run: pnpm run build

      - name: ðŸ“¦ Prepare deployment
        run: |
          cd out
          tar -czf ../deploy.tar.gz .

      - name: ðŸ” Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: ðŸ§¹ Clean remote directory
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} '
          mkdir -p beta &&
          cd beta &&
          find . -mindepth 1 -maxdepth 1 ! -name "docs" ! -name "images" -exec rm -rf {} +'

      - name: ðŸ“‚ Transfer and extract files
        run: |
          scp deploy.tar.gz ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:beta/
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} '
          cd beta &&
          tar -xzf deploy.tar.gz &&
          rm deploy.tar.gz'
